name: CI

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print hello from linux
      run: echo Hello, world!

    - name: Get date
      run: datetime
  
  job2:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print hellow from windows
      run: echo Hello, world!

    - name: Get date
      run: get-date
  
  job3:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print hello from Mac
      run: echo Hello, world!

    - name: Get date
      run: datetime
  
  job4:
    needs: [job1,job2,job3]

    steps:
    - uses: actions/checkout@v4

    - name: Print final message
      run: echo Hello, world!

